# Пример конфигурации dashboard-light
auth:
  provider: gitlab
  gitlab_url: "https://gitlab.example.com"
  client_id: "your-gitlab-client-id"
  client_secret_env: "GITLAB_CLIENT_SECRET"
  redirect_uri: "https://dashboard.example.com/auth/callback"

  # Роли и группы GitLab
  roles:
    viewer:
      gitlab_groups: ["developers", "qa"]
    admin:
      gitlab_groups: ["devops-team"]

  # Права по ролям
  permissions:
    viewer:
      menu_items: ["status"]
      allowed_namespace_patterns: ["^project-.*-staging$", "^common-.*"]
      allowed_clusters: ["staging-cluster"]
    admin:
      menu_items: ["status", "admin_settings"]
      allowed_namespace_patterns: [".*"]
      allowed_clusters: ["*"]

  # Настройки анонимного доступа
  allow_anonymous_access: false
  anonymous_role: "viewer"

# Настройки UI
ui:
  refresh_interval_seconds: 15
  status_colors:
    deployment:
      healthy: "#28a745"
      progressing: "#ffc107"
      scaled_zero: "#6c757d"
      error: "#dc3545"
    pod:
      running: "#28a745"
      succeeded: "#17a2b8"
      pending: "#ffc107"
      failed: "#dc3545"
      terminating: "#6c757d"

# Настройки меню
menu:
  - id: status
    title: "Status"
    icon: "icon-status"
    required_role: "viewer"
